### PR TITLE
Add wit-deps.toml

### PR DESCRIPTION
**Pull request by Mossaka**
This PR adds wit-deps manifest file. 

You can run `wit-deps update` to update its deps.

### CODE REVIEW

**Review by pchickey — COMMENTED** [review]
Thanks for integrating this with the tool! Can we add a CI check to ensure that the checked-in sources are up to date?

**Comment by Mossaka** [comment]
> Thanks for integrating the wit-deps tool! Can we add a CI check to ensure that the checked-in sources are up to date?

Something like a `wit-deps check` command?

**Comment by pchickey** [comment]
This is the implementation we used when integrating it with the preview2-prototyping repo https://github.com/bytecodealliance/preview2-prototyping/blob/dd34a00d4386000cd00071cff18b9e3a12788075/.github/workflows/main.yml#L82-L86

**Comment by Mossaka** [comment]
That looks great! I can add it to the CI check here.

**Review by pchickey — COMMENTED** [review]
Thanks! Looks like the wit-abi tool needs to be updated and the new md checked in

**Comment by sunfishcode** [comment]
I created https://github.com/WebAssembly/wasi-tools/pull/15 to update the wit-abi tool. We can regenerate the files and fix the CI here once that's propagated through.

**Pull request merged**
