### PR TITLE
chore: add w3c license to repository

### PR DESCRIPTION
**Pull request by eduardomourar**
This PR only adds the ~~Apache 2.0 license based on the same one from the design repository [here](https://github.com/WebAssembly/design/blob/main/LICENSE)~~ W3C license to this repository.

### CODE REVIEW

**Comment by sunfishcode** [comment]
If we're going to change the license, we should do so in the [proposal template repo](https://github.com/WebAssembly/wasi-proposal-template/) first, and then we can update all the proposals to follow it.

Also fwiw, the Wasm spec document uses [this W3C license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document), and it's worth considering that for WASI spec documents too, since they are just interfaces, and not implementations.

**Comment by eduardomourar** [comment]
I have created this PR to include the license to the template: https://github.com/WebAssembly/wasi-proposal-template/pull/9 and modified the one here to use the W3C license as suggested.

**Comment by pchickey** [comment]
https://github.com/WebAssembly/wasi-proposal-template/pull/11 is now the correct way to specify this license - can you update this PR?

**Comment by eduardomourar** [comment]
@pchickey , done

**Pull request merged**
